# Generated by Django 4.2.3 on 2023-08-22 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('college_website', models.CharField(max_length=200)),
                ('event_datetime', models.DateTimeField(blank=True, null=True)),
                ('event_description', models.TextField()),
                ('event_brochure', models.FileField(blank=True, null=True, upload_to='event_brochures/')),
                ('coordinator_name', models.CharField(max_length=100)),
                ('coordinator_contact', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
